
Warning: Things Are About to Get Real

This is a Good Thing, because it will be a genuine character-building Learning Experience™.

```
(venv) (base) 20/05/29 5:01:00 kvogel-macbook-2018:~/p/python/tdd/testinggoat ±(master) ✗
❯ python manage.py startapp lists
❯ ls lists
__init__.py  admin.py     apps.py      migrations/  models.py    tests.py     views.py
❯ ls superlists
__init__.py  __pycache__/ settings.py  urls.py      wsgi.py
```

Unit Tests, and How They Differ from Functional Tests

functional tests test the application from the outside, from the point of view of the user. 
Unit tests test the application from the inside, from the point of view of the programmer.

The TDD approach we're following wants our application to be *covered* by *both types of test*.
Our workflow will look a bit like this:

* We start by writing a functional test, describing the new functionality from the user’s point of view.

* Once we have a functional test that fails, we start to think about how to write code that can get it to pass (or at least to get past its current failure). We now use one or more unit tests to define how we want our code to behave — ​the idea is that *each line* of production code we write should be tested by (at least) one of our unit tests.

* Once we have a failing unit test, we write the smallest amount of application code we can, just enough to get the unit test to pass. We may iterate between steps 2 and 3 a few times, until we think the functional test will get a little further.

* Now we can rerun our functional tests and see if they pass, or get a little further. That may prompt us to write some new unit tests, and some new code, and so on.

*the functional tests are driving what development we do from a high level, while the unit tests drive what we do at a low level*.

Unit Testing in Django

lists/tests.py
```py
from django.test import TestCase

# Create your tests here.
```

Django has helpfully suggested we use a special version of TestCase, which it provides. It’s an augmented version of the standard unittest.TestCase, with some additional Django-specific features

```py
class SmokeTest(TestCase):

    def test_bad_maths(self):
        self.assertEqual(1+1, 3)
```   

```
(venv) 20/05/29 4:38:24 kvogel-macbook-2018:~/Projects/python/tdd/testinggoat ±(master) ✗ 
❯ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F
======================================================================
FAIL: test_bad_maths (lists.tests.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kvogel/Projects/python/tdd/testinggoat/lists/tests.py", line 8, in test_bad_maths
    self.assertEqual(1+1, 3)
AssertionError: 2 != 3
----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...
```


git: The key rule is: make sure you always review what you’re about to commit before you do it.


as with any web server, Django’s main job is to decide what to do when a user asks for a particular URL on our site. Django’s workflow goes something like this:

An HTTP request comes in for a particular URL.
Django uses some rules to decide which view function should deal with the request (this is referred to as resolving the URL).
The view function processes the request and returns an HTTP response.

```py
class HomePageTest(TestCase):

    def test_root_url_resolves_to_home_page_view(self):
        found = resolve('/')
        self.assertEqual(found.func, home_page)
```

```
(venv) (base) 20/05/29 5:20:15 kvogel-macbook-2018:~/p/python/tdd/testinggoat ±(master) ✗
❯ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: lists.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lists.tests
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/kvogel/Projects/python/tdd/testinggoat/lists/tests.py", line 3, in <module>
    from lists.views import home_page
ImportError: cannot import name 'home_page'
----------------------------------------------------------------------
Ran 1 test in 0.000s
FAILED (errors=1)
Destroying test database for alias 'default'...
```

for the purposes of TDD, an exception which was predicted counts as an expected failure. Since we have both a failing functional test and a failing unit test, we have the Testing Goat’s full blessing to code away.

Be warned, TDD means that long periods of anticipation are only defused very gradually, and by tiny increments.

